// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://zorqkahwojneoryarvia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvcnFrYWh3b2puZW9yeWFydmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMjI1MzYsImV4cCI6MjA4NTc5ODUzNn0.8_yl8KOKXiOgQo0eySxGPAyswonKH955hhfyfUoB9RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
